services:
  web-fe:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    networks:
      - counter-net
    volumes:
      - counter-vol:/code
  redis:
    image: redis:alpine
    networks:
      - counter-net

networks:
  counter-net:

volumes:
  counter-vol:
