services:
  my-app:
    #build: .
    image: danenja/my-mongo-app:1.0
    ports:
     - 3000:3000
    environment:
      MONGO_DB_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_DB_PWD: ${MONGO_ADMIN_PASS}
    container_name: my-app
    networks:
      - mongo-network

  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
    container_name: mongodb
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS}
      ME_CONFIG_MONGODB_SERVER: mongodb
    container_name: mongo-express
    depends_on:
     - "mongodb"
    networks:
      - mongo-network

networks:
  mongo-network:
    name: mongo-network
